### ISSUE TITLE
TecaherGPT and MathGPT launched by Byju's Wiz

### ISSUE THREAD

**Issue by ArijitSinghEDA** [LouCodingStuff/TeacherGPT#1]
Are TeacherGPT and MathGPT, launched by Byju's wiz recently, the same proposed here?

**Comment by Cyber-Gwen** [comment]
Hi, 
im not sure what you are talking about or who Byju is. I created these prompts by myself alone.
Feel free to ask any more questions :D

**Comment by ArijitSinghEDA** [comment]
I just recently came across an article stating the launch of LLM models by Byju's wiz where I read about their TeacherGPT and MathGPT, which intrigued me, so I searched online and came across your repo.

Can you explain how one can use the prompts you have created?

**Comment by Cyber-Gwen** [comment]
im assuming the article you are talking about is [this](https://www.medianama.com/2023/06/223-byjus-ai-suite-induct-generative-ai-educational-products/)

I'm afraid I have nothing to do with this, as the company mentioned in the article has made its own AI model or is using the API of an existing one. Whereas all mine does is give the user a prompt to access the full capabilities of chat models like ChatGPT. 


To use what I have created you simply need to copy and paste the respective prompt into the AI model of your choosing and then continue the conversation.
